// ----------------------------------------------
//
// AUTOGENERATED FILE, DO NOT EDIT
//
// ----------------------------------------------

import t from "flow-runtime";
export const SomeString = t.type("SomeString", t.string());

export const SomeObject = t.type("SomeObject", t.object(t.property("innerString", SomeString), t.property("count", t.number())));